apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: telegram
  labels:
    alertmanagerConfig: telegram
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'telegram'
  receivers:
  - name: 'telegram'
    telegramConfigs:
    - botToken:
        key: token
      chatID: {{ .Values.telegram.chat_id }}
      sendResolved: true
